// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkmrtjxhyctfqqwenqbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrbXJ0anhoeWN0ZnFxd2VucWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDE3NTAsImV4cCI6MjA3MTE3Nzc1MH0.aE-7MHBjfSDjDUIIClndHc7pLiYkbnTP37XpUl8_LQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});